import { Theme } from '../types/index.js';

export const ICONS_PER_LINE = 15;
export const THEMES: Theme[] = ['light', 'dark'];

export const CONTENT = {
  JSON: {
    'Content-Type': 'application/json;charset=UTF-8',
    'Cache-Control': 'public, max-age=86400, stale-while-revalidate=3600',
    ETag: '"icons-json-tag"',
    Vary: 'Accept-Encoding',
  },
  HTML: {
    'Content-Type': 'text/html;charset=UTF-8',
    'Cache-Control': 'public, max-age=86400, stale-while-revalidate=3600',
    ETag: '"icons-html-tag"',
    Vary: 'Accept-Encoding',
  },
  SVG: {
    'Content-Type': 'image/svg+xml',
    'Cache-Control':
      'public, max-age=31536000, immutable, stale-while-revalidate=86400',
    ETag: '"icons-svg-tag"',
    Vary: 'Accept-Encoding',
  },
};

export const ERRORS = {
  INVALID_THEME: `Theme must be ${THEMES.join(' or ')}`,
  INVALID_PERLINE: 'Icons per line must be a number between 1 and 50',
  NO_ICON_PARAM: 'You must specify ?i=icon1,icon2 or i=all',
  NO_ICONS_FOUND: 'No valid icons found from the given parameters',
  NOT_FOUND: 'Not found',
};

export const shortNames: Record<string, string> = {
  js: 'javascript',
  ts: 'typescript',
  py: 'python',
  rb: 'ruby',
  rs: 'rust',
  go: 'golang',
  cs: 'csharp',
  'c#': 'csharp',
  cpp: 'cplusplus',
  'c++': 'cplusplus',
  sh: 'bash',
  zsh: 'zshell',
  bat: 'batch',
  pwsh: 'powershell',
  ps1: 'powershell',
  md: 'markdown',
  wasm: 'webassembly',
  vb: 'visualbasic',
  sc: 'scala',
  asm: 'assembly',
  tailwind: 'tailwindcss',
  tw: 'tailwindcss',
  vue: 'vuejs',
  nuxt: 'nuxtjs',
  react: 'reactjs',
  next: 'nextjs',
  angular: 'angularjs',
  ng: 'angularjs',
  svelte: 'svelte',
  sv: 'svelte',
  bs: 'bootstrap',
  mui: 'materialui',
  windi: 'windicss',
  bulma: 'bulmacss',
  post: 'postcss',
  express: 'expressjs',
  nest: 'nestjs',
  dj: 'django',
  drf: 'djangorestframework',
  flask: 'flask',
  fast: 'fastapi',
  sb: 'springboot',
  spring: 'springboot',
  gql: 'graphql',
  ktorio: 'ktor',
  aws: 'amazonwebservices',
  amz: 'amazonwebservices',
  gcp: 'googlecloud',
  cf: 'cloudflare',
  k8s: 'kubernetes',
  pod: 'podman',
  ans: 'ansible',
  tf: 'terraform',
  do: 'digitalocean',
  pg: 'postgresql',
  pgsql: 'postgresql',
  mongo: 'mongodb',
  elk: 'elasticsearch',
  rmq: 'rabbitmq',
  mac: 'macos',
  win: 'windows',
  arch: 'archlinux',
  alpine: 'alpinelinux',
  gh: 'github',
  gl: 'gitlab',
  bb: 'bitbucket',
  ghactions: 'githubactions',
  vs: 'visualstudio',
  vscode: 'visualstudiocode',
  idea: 'intellijidea',
  ij: 'intellijidea',
  vi: 'vim',
  nvim: 'neovim',
  rollup: 'rollupjs',
  esb: 'esbuild',
  ps: 'adobephotoshop',
  ai: 'adobeillustrator',
  pr: 'adobepremiere',
  ae: 'adobeaftereffects',
  id: 'adobeindesign',
  au: 'adobeaudition',
  np: 'numpy',
  pd: 'pandas',
  plt: 'matplotlib',
  sklearn: 'scikitlearn',
  ga: 'googleanalytics',
  chart: 'chartjs',
  gr: 'gradio',
  st: 'streamlit',
  langchain: 'langchain',
  bots: 'discordbots',
  gatsbyjs: 'gatsby',
  unreal: 'unrealengine',
  fcad: 'freecad',
  gas: 'googleappsscript',
  fm: 'framermotion',
  o365: 'microsoftoffice',
  word: 'microsoftword',
  pp: 'microsoftpowerpoint',
  msteams: 'microsoftteams',
};
